---
title: "Grafícos"
---
Histograma

```{r}
trees
hist(trees$Height)
hist(trees$Height, main = "Árvores", ylab="Frequencia", xlab="Altura", col="blue")
hist(trees$Height, main = "Árvores", ylab="Frequencia", xlab="Altura", col="blue",
     density = 20, breaks = 20)
```

Densidade

```{r}
densidade = density(trees$Height)
plot(densidade)
```

Densidade sobre o histograma

````{r}
hist(trees$Height, main = NULL, xlab = NULL)
par(new=TRUE)
plot(densidade)
```

Dispersão

```{r}
plot(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Volume, main = "Árvores")
plot(trees$Girth, trees$Volume, main = "Árvores", xlab="Circunferencia", ylab = "Volume", col="blue")
#pch muda o elemento grafico
plot(trees$Girth, trees$Volume, main = "Árvores", xlab="Circunferencia", ylab = "Volume", col="blue", pch=20)
```
Muda o  tipo

```{r}
plot(trees$Girth, trees$Volume, main = "Árvores", xlab="Circunferencia", ylab = "Volume", col="blue", pch=20, type='l')
```

Tremulação, diminui sobre posição

```{r}
plot(jitter(trees$Girth), trees$Volume, ylab = "Circunferência", xlab = "Volume", col = "blue", main="Árvores")
```

Legenda com dimenção categórica

```{r}
plot(CO2$conc, CO2$uptake, pch=20, col=CO2$Treatment)
legend("bottomright", legend = c("nonchilled", "chilled"), cex=1, fill=c("black","red"))
```

Novos dados

```{r}
plot(trees)
```

Divisão da tela

```{r}
split.screen(figs=c(2,2))
screen(1)
plot(trees$Girth, trees$Volume)
screen(2)
plot(trees$Girth, trees$Height)
screen(3)
plot(trees$Height, trees$Volume)
screen(4)
hist(trees$Volume)
close.screen(all=TRUE)
```