---
title: "Mutilayes"
---

```{r}
library(neuralnet)
library(mltools)
library(data.table)
library(caret)
```

Dimencionamento de Caracteristicas - Padronizaçã

```{r}
iris2 = scale(iris[,1:4])
iris2 = as.data.frame(iris2)
# add class
iris2$Species = iris$Species
iris2
```

Dividimos em treino e teste, com o metodo caret

```{r}
set.seed(1234)
particao = createDataPartition(1:dim(iris2)[1], p=.7)
iristreino = iris2[particao$Resample1,]
iristeste = iris2[- particao$Resample1,]
dim(iristreino)
dim(iristeste)
```

One hot encoding para a classe

```{r}
#juntamos os atributos com a classe para não perde-los
iristreino = cbind(iristreino[,1:4], one_hot(as.data.table(iristreino[,5])))
iristreino
```

Modelo

```{r}
modelo = neuralnet(V1_setosa + V1_versicolor + V1_virginica ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, iristreino, hidden=c(5,4))
print(modelo)
plot(modelo)
```

Previsão

```{r}
teste = compute(modelo, iristeste[,1:4])
teste$net.result
resultado = as.data.frame(teste$net.result)
resultado
```

Atribuimos nomes as colunas conforme a classe

```{r}
names(resultado)[1] <- 'setosa'
names(resultado)[3] <- 'versicolor'
names(resultado)[3] <- 'virginica'
resultado
```

Usamos o nome das colunas para preencher uma coluna com a classe

```{r}
resultado$class = colnames(resultado[,1:3])[max.col(resultado[,1:3], ties.method = "first")]
resultado
```

Avaliamos a performance

```{r}
confusao = table(resultado$class, iristeste$Species)
confusao
sum(diag(confusao) * 100 / sum(confusao))
```